(() => {
  const cfg=window.RECRUITING_OS_CONFIG||{};const root=document.getElementById('applyContent');
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  if(!cfg.supabaseUrl||!cfg.supabasePublishableKey){root.innerHTML='<div class="error">Konfiguration fehlt.</div>';return;}
  const sb=window.supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey);
  const slug=new URLSearchParams(location.search).get('f');let funnel=null;
  async function load(){if(!slug){root.innerHTML='<div class="error">Funnel-Link ist unvollständig.</div>';return;}const res=await fetch(`${cfg.supabaseUrl}/functions/v1/public-funnel?slug=${encodeURIComponent(slug)}`,{headers:{apikey:cfg.supabasePublishableKey,Authorization:`Bearer ${cfg.supabasePublishableKey}`}});const body=await res.json();if(!res.ok){root.innerHTML=`<div class="error">${esc(body.error||'Funnel nicht verfügbar.')}</div>`;return;}funnel=body.funnel;render();}
  function render(){const job=funnel.job||{};root.innerHTML=`<header><h1>${esc(funnel.headline||job.title||'Jetzt bewerben')}</h1><p class="lead">${esc(funnel.intro_text||'Bewirb dich schnell und unkompliziert – ohne Anschreiben.')}</p><div class="job-meta"><span class="pill">${esc(job.title||'Position')}</span>${job.company?.name?`<span class="pill">${esc(job.company.name)}</span>`:''}${job.location?`<span class="pill">${esc(job.location)}</span>`:''}</div></header><form id="applyForm" class="apply-form"><div><label>Vorname *</label><input name="first_name" required></div><div><label>Nachname *</label><input name="last_name" required></div><div><label>E-Mail *</label><input name="email" type="email" required></div><div><label>Telefon</label><input name="phone" type="tel"></div>${(funnel.questions||[]).map(questionField).join('')}<label class="consent full"><input name="consent" type="checkbox" required><span>${esc(funnel.privacy_text)}</span></label><div class="full"><button id="applyButton" class="apply-button" type="submit">Bewerbung absenden</button><div id="applyMessage" class="message"></div></div></form>`;document.getElementById('applyForm').onsubmit=submit;}
  function questionField(q){const req=q.required?'required':'';const cls=q.type==='textarea'?'full':'';let field;if(q.type==='select')field=`<select name="q_${esc(q.id)}" ${req}><option value="">Bitte auswählen</option>${(q.options||[]).map(o=>`<option>${esc(o)}</option>`).join('')}</select>`;else if(q.type==='textarea')field=`<textarea name="q_${esc(q.id)}" ${req}></textarea>`;else field=`<input name="q_${esc(q.id)}" ${req}>`;return `<div class="${cls}"><label>${esc(q.label)}${q.required?' *':''}</label>${field}</div>`;}
  async function submit(e){e.preventDefault();const form=new FormData(e.currentTarget),answers={};(funnel.questions||[]).forEach(q=>answers[q.id]=String(form.get(`q_${q.id}`)||'').trim());const button=document.getElementById('applyButton'),message=document.getElementById('applyMessage');button.disabled=true;button.textContent='Wird gesendet …';const res=await fetch(`${cfg.supabaseUrl}/functions/v1/submit-funnel-application`,{method:'POST',headers:{'Content-Type':'application/json',apikey:cfg.supabasePublishableKey,Authorization:`Bearer ${cfg.supabasePublishableKey}`},body:JSON.stringify({slug,first_name:form.get('first_name'),last_name:form.get('last_name'),email:form.get('email'),phone:form.get('phone'),answers,consent_given:form.get('consent')==='on'})});const body=await res.json();if(!res.ok){message.textContent=body.error||'Bewerbung konnte nicht gesendet werden.';message.className='message error';button.disabled=false;button.textContent='Bewerbung absenden';return;}root.innerHTML=`<div class="thank-you"><strong>✓</strong><h2>Bewerbung angekommen</h2><p class="lead">${esc(body.thank_you_text||funnel.thank_you_text)}</p></div>`;}
  load();
})();
