(() => {
  const cfg=window.RECRUITING_OS_CONFIG||{}; if(!cfg.supabaseUrl||!cfg.supabasePublishableKey||!window.supabase)return;
  const db=window.supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
  let org=null,campaigns=[],funnels=[];
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  async function ensureOrg(){if(org)return org;const{data}=await db.rpc('my_organizations');org=data?.[0]?.organization_id;return org;}
  function defaultQuestions(c){const title=c?.job?.title||'diese Position';return [
    {id:'experience',label:`Wie viele Jahre relevante Erfahrung hast du für ${title}?`,type:'select',required:true,options:['Keine','Unter 1 Jahr','1–3 Jahre','3–5 Jahre','Mehr als 5 Jahre']},
    {id:'availability',label:'Wann könntest du starten?',type:'text',required:true},
    {id:'salary',label:'Wie hoch ist deine Gehaltsvorstellung?',type:'text',required:false},
    {id:'location',label:'Aus welchem Ort kommst du?',type:'text',required:true},
    {id:'motivation',label:'Warum interessiert dich diese Position?',type:'textarea',required:false}
  ];}
  async function load(){const id=await ensureOrg();if(!id)return;const[c,f]=await Promise.all([
    db.from('recruiting_campaigns').select('id,name,job_id,job:jobs(title,location,company:companies(name))').eq('organization_id',id).order('created_at',{ascending:false}),
    db.from('application_funnels').select('*,campaign:recruiting_campaigns(name),job:jobs(title,company:companies(name))').eq('organization_id',id).order('created_at',{ascending:false})
  ]);campaigns=c.data||[];funnels=f.data||[];renderIntoAds();}
  function renderIntoAds(){const root=document.querySelector('#recruitingAds .ads-layout');if(!root)return;let box=document.getElementById('funnelManager');if(!box){box=document.createElement('section');box.id='funnelManager';box.className='section funnel-manager';root.appendChild(box);}box.innerHTML=`<div class="section-head"><div><h2>Bewerbungsfunnels</h2><p class="muted">Mobile Landingpages für Kampagnen und Vakanzen.</p></div><button id="newFunnelBtn" class="btn primary">+ Funnel erstellen</button></div><div class="funnel-list">${funnels.map(card).join('')||'<div class="ads-empty">Noch kein Bewerbungsfunnel vorhanden.</div>'}</div>`;document.getElementById('newFunnelBtn').onclick=openCreate;box.querySelectorAll('[data-publish]').forEach(b=>b.onclick=()=>publish(b.dataset.publish));box.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>copyLink(b.dataset.copy));}
  function card(f){const url=`${location.origin}${location.pathname.replace(/index\.html$/,'')}apply.html?f=${encodeURIComponent(f.slug)}`;return `<article class="funnel-card"><div><h3>${esc(f.name)}</h3><p class="muted">${esc(f.job?.title||'Vakanz')} · ${esc(f.job?.company?.name||'')}</p><div class="campaign-meta"><span class="badge ${f.status==='published'?'green':'blue'}">${esc(f.status)}</span><span class="badge">${(f.questions||[]).length} Fragen</span></div></div><div class="campaign-actions">${f.status!=='published'?`<button class="btn primary" data-publish="${f.id}">Veröffentlichen</button>`:''}<button class="btn" data-copy="${esc(url)}">Link kopieren</button><a class="btn" href="${esc(url)}" target="_blank" rel="noreferrer">Vorschau</a></div></article>`;}
  function openCreate(){const modal=document.getElementById('adsModal'),content=document.getElementById('adsModalContent');document.getElementById('adsModalTitle').textContent='Bewerbungsfunnel erstellen';content.innerHTML=`<form id="funnelForm" class="ads-form"><div class="full-span"><label>Kampagne</label><select name="campaign_id" required><option value="">Bitte auswählen</option>${campaigns.map(c=>`<option value="${c.id}">${esc(c.name)} · ${esc(c.job?.title||'')}</option>`).join('')}</select></div><div class="full-span"><label>Funnelname</label><input name="name" required placeholder="z. B. Bewerbung Steuerfachangestellte Frankfurt"></div><div class="full-span"><label>Überschrift</label><input name="headline" placeholder="Dein nächster Karriereschritt beginnt hier"></div><div class="full-span"><label>Einleitung</label><textarea name="intro_text" placeholder="Bewirb dich in weniger als zwei Minuten – ohne Anschreiben."></textarea></div><div class="full-span"><label>Danke-Text</label><textarea name="thank_you_text">Vielen Dank! Wir melden uns schnellstmöglich bei dir.</textarea></div><div class="full-span modal-actions"><button type="submit" class="btn primary">Funnel anlegen</button></div><div id="funnelMessage" class="message full-span"></div></form>`;modal.classList.add('open');document.getElementById('funnelForm').onsubmit=create;}
  async function create(e){e.preventDefault();const f=new FormData(e.currentTarget),campaign=campaigns.find(x=>x.id===f.get('campaign_id'));if(!campaign)return;const slug=`${String(campaign.job?.title||'bewerbung').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}-${crypto.randomUUID().slice(0,8)}`;const{data:{user}}=await db.auth.getUser();const payload={organization_id:org,campaign_id:campaign.id,job_id:campaign.job_id,name:String(f.get('name')).trim(),slug,headline:String(f.get('headline')||'').trim()||campaign.job?.title,intro_text:String(f.get('intro_text')||'').trim(),thank_you_text:String(f.get('thank_you_text')||'').trim(),questions:defaultQuestions(campaign),created_by:user?.id};const{error}=await db.from('application_funnels').insert(payload);if(error){document.getElementById('funnelMessage').textContent=error.message;return;}document.getElementById('adsModal').classList.remove('open');await load();}
  async function publish(id){const{error}=await db.from('application_funnels').update({status:'published',published_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',id);if(error)return alert(error.message);await load();}
  async function copyLink(url){await navigator.clipboard.writeText(url);alert('Funnel-Link kopiert.');}
  const obs=new MutationObserver(()=>{if(document.getElementById('recruitingAds'))load();});obs.observe(document.body,{childList:true,subtree:true});
})();
