(() => {
  const cfg = window.RECRUITING_OS_CONFIG || {};
  const sb = window.supabase.createClient(cfg.supabaseUrl, cfg.supabasePublishableKey, {auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
  const statusEl=document.getElementById('googleStatus'), connectBtn=document.getElementById('connectGoogle'), disconnectBtn=document.getElementById('disconnectGoogle'), msg=document.getElementById('message');
  const say=(t,e=false)=>{msg.textContent=t||'';msg.style.color=e?'var(--red)':'var(--yellow)'};
  async function currentOrg(){const {data:{session}}=await sb.auth.getSession();if(!session){location.href='./index.html';return null;}const {data,error}=await sb.rpc('my_organizations');if(error||!data?.length){say(error?.message||'Keine Organisation gefunden.',true);return null;}return data[0].organization_id;}
  async function refresh(){const org=await currentOrg();if(!org)return;const {data,error}=await sb.from('integrations').select('*').eq('organization_id',org).eq('provider','google').maybeSingle();if(error){say(error.message,true);return;}const connected=data?.status==='connected';statusEl.textContent=connected?`Verbunden: ${data.account_email||'Google'}`:'Nicht verbunden';statusEl.classList.toggle('connected',connected);connectBtn.classList.toggle('hidden',connected);disconnectBtn.classList.toggle('hidden',!connected);}
  connectBtn.onclick=async()=>{say('Google-OAuth wird vorbereitet …');const {data:{session}}=await sb.auth.getSession();if(!session)return location.href='./index.html';const returnTo=location.origin+location.pathname;const {data,error}=await sb.functions.invoke('google-oauth-start',{body:{return_to:returnTo},headers:{Authorization:`Bearer ${session.access_token}`}});if(error||!data?.url){say(error?.message||'OAuth-Funktion ist noch nicht bereit.',true);return;}location.href=data.url;};
  disconnectBtn.onclick=async()=>{const org=await currentOrg();if(!org)return;const {error}=await sb.from('integrations').update({status:'disconnected',access_token_encrypted:null,refresh_token_encrypted:null,updated_at:new Date().toISOString()}).eq('organization_id',org).eq('provider','google');if(error)return say(error.message,true);say('Google-Verbindung getrennt.');refresh();};
  const p=new URLSearchParams(location.search);if(p.get('google')==='connected')say('Google Workspace wurde erfolgreich verbunden.');if(p.get('google_error'))say(p.get('google_error'),true);refresh();
})();