(() => {
  const cfg = window.RECRUITING_OS_CONFIG || {};
  if (!cfg.supabaseUrl || !cfg.supabasePublishableKey || !window.supabase) return;
  const db = window.supabase.createClient(cfg.supabaseUrl, cfg.supabasePublishableKey, { auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true} });
  let organizationId=null, jobs=[], campaigns=[];
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=v=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(Number(v||0));
  const statusLabel={draft:'Entwurf',generated:'Generiert',approved:'Freigegeben',paused:'Pausiert',active:'Aktiv',completed:'Abgeschlossen',archived:'Archiviert'};

  async function ensureOrg(){ if(organizationId)return organizationId; const {data}=await db.rpc('my_organizations'); organizationId=data?.[0]?.organization_id||null; return organizationId; }
  function injectView(){
    const nav=document.querySelector('.nav'); if(!nav||document.querySelector('[data-view="recruitingAds"]')) return;
    const btn=document.createElement('button'); btn.dataset.view='recruitingAds'; btn.textContent='Recruiting Ads'; const integrations=nav.querySelector('a'); nav.insertBefore(btn,integrations||null);
    const main=document.querySelector('.main'); if(!main)return;
    const section=document.createElement('section'); section.id='recruitingAds'; section.className='view'; section.innerHTML=`<div class="ads-layout"><div class="ads-hero"><div><h2>Recruiting Ads Cockpit</h2><p class="muted">Aus einer Vakanz in wenigen Minuten ein vollständiges Meta-Recruiting-Kampagnenpaket erstellen.</p></div><button id="newCampaignBtn" class="btn primary">+ Kampagne erstellen</button></div><div class="ads-stats"><div class="ads-stat"><small>Kampagnen</small><strong id="adsTotal">0</strong></div><div class="ads-stat"><small>Entwürfe</small><strong id="adsDrafts">0</strong></div><div class="ads-stat"><small>Freigegeben</small><strong id="adsApproved">0</strong></div><div class="ads-stat"><small>Geplantes Budget</small><strong id="adsBudget">0 €</strong></div></div><div class="section"><div class="section-head"><h2>Kampagnen</h2><button id="adsRefresh" class="btn">Aktualisieren</button></div><div id="campaignList" class="campaign-list"></div></div></div>`;
    main.appendChild(section);
    btn.addEventListener('click',async()=>{document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));section.classList.add('active');document.getElementById('pageTitle').textContent='Recruiting Ads';document.getElementById('newBtn').classList.add('hidden');await load();});
    document.querySelectorAll('.nav button:not([data-view="recruitingAds"])').forEach(x=>x.addEventListener('click',()=>document.getElementById('newBtn').classList.remove('hidden')));
    document.getElementById('newCampaignBtn').onclick=openCreate;
    document.getElementById('adsRefresh').onclick=load;
    injectModal();
  }
  function injectModal(){ if(document.getElementById('adsModal'))return; document.body.insertAdjacentHTML('beforeend',`<div id="adsModal" class="ads-modal"><div class="ads-modal-card"><div class="section-head"><h2 id="adsModalTitle">Kampagne erstellen</h2><button class="btn" data-ads-close>Schließen</button></div><div id="adsModalContent"></div></div></div>`); document.querySelector('[data-ads-close]').onclick=()=>document.getElementById('adsModal').classList.remove('open'); }
  async function load(){const org=await ensureOrg(); if(!org)return; const [j,c]=await Promise.all([db.from('jobs').select('*,company:companies(name)').eq('organization_id',org).order('created_at',{ascending:false}),db.from('recruiting_campaigns').select('*,job:jobs(title,company:companies(name))').eq('organization_id',org).order('created_at',{ascending:false})]); jobs=j.data||[]; campaigns=c.data||[]; render();}
  function render(){document.getElementById('adsTotal').textContent=campaigns.length;document.getElementById('adsDrafts').textContent=campaigns.filter(x=>x.status==='draft'||x.status==='generated').length;document.getElementById('adsApproved').textContent=campaigns.filter(x=>x.status==='approved').length;document.getElementById('adsBudget').textContent=money(campaigns.reduce((s,x)=>s+Number(x.daily_budget||0)*Number(x.duration_days||0),0));document.getElementById('campaignList').innerHTML=campaigns.map(c=>`<article class="campaign-card"><div><h3>${esc(c.name)}</h3><p class="muted">${esc(c.job?.title||'Vakanz')} · ${esc(c.job?.company?.name||'')}</p><div class="campaign-meta"><span class="badge blue">${esc(statusLabel[c.status]||c.status)}</span><span class="badge">${money(c.daily_budget)}/Tag</span><span class="badge">${esc(c.duration_days||0)} Tage</span><span class="badge">EMPLOYMENT</span></div></div><div class="campaign-actions">${c.generation_status==='completed'?`<button class="btn" data-view-package="${c.id}">Paket ansehen</button>`:`<button class="btn primary" data-generate="${c.id}">${c.generation_status==='processing'?'Generiert …':'Mit KI generieren'}</button>`}${c.status==='generated'?`<button class="btn primary" data-approve="${c.id}">Freigeben</button>`:''}</div></article>`).join('')||'<div class="ads-empty">Noch keine Recruiting-Kampagne angelegt.</div>';document.querySelectorAll('[data-generate]').forEach(b=>b.onclick=()=>generate(b.dataset.generate));document.querySelectorAll('[data-view-package]').forEach(b=>b.onclick=()=>showPackage(b.dataset.viewPackage));document.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>approve(b.dataset.approve));}
  function openCreate(){document.getElementById('adsModalTitle').textContent='Recruiting-Kampagne erstellen';document.getElementById('adsModalContent').innerHTML=`<form id="campaignForm" class="ads-form"><div class="full-span"><label>Vakanz</label><select name="job_id" required><option value="">Bitte auswählen</option>${jobs.filter(j=>j.status==='active'||j.status==='draft').map(j=>`<option value="${j.id}">${esc(j.title)} · ${esc(j.company?.name||'')}</option>`).join('')}</select></div><div class="full-span"><label>Kampagnenname</label><input name="name" required placeholder="z. B. Steuerfachangestellte Frankfurt – August"></div><div><label>Tagesbudget</label><input name="daily_budget" type="number" min="1" required value="50"></div><div><label>Laufzeit in Tagen</label><input name="duration_days" type="number" min="1" required value="30"></div><div><label>Radius in km</label><input name="radius_km" type="number" min="1" value="40"></div><div><label>Zielkosten pro Bewerbung</label><input name="target_cpl" type="number" min="1" value="40"></div><div><label>Gesuchte Einstellungen</label><input name="hires_needed" type="number" min="1" value="1"></div><div><label>Special Ad Category</label><input value="EMPLOYMENT" disabled></div><div class="full-span"><label>Arbeitgebervorteile, durch Komma getrennt</label><input name="benefits" placeholder="Homeoffice, Weiterbildung, 30 Tage Urlaub"></div><div class="full-span"><label>Zielgruppen- und Kontextnotizen</label><textarea name="audience_notes" placeholder="Was muss die KI über Zielgruppe und Arbeitgeber wissen?"></textarea></div><div class="full-span modal-actions"><button class="btn" type="button" data-ads-cancel>Abbrechen</button><button class="btn primary" type="submit">Kampagne anlegen</button></div><div id="campaignMessage" class="message full-span"></div></form>`;document.getElementById('adsModal').classList.add('open');document.querySelector('[data-ads-cancel]').onclick=()=>document.getElementById('adsModal').classList.remove('open');document.getElementById('campaignForm').onsubmit=createCampaign;}
  async function createCampaign(e){e.preventDefault();const f=new FormData(e.currentTarget);const payload={organization_id:organizationId,job_id:f.get('job_id'),name:f.get('name').trim(),daily_budget:Number(f.get('daily_budget')),duration_days:Number(f.get('duration_days')),radius_km:Number(f.get('radius_km')||0)||null,target_cpl:Number(f.get('target_cpl')||0)||null,hires_needed:Number(f.get('hires_needed')||1),benefits:String(f.get('benefits')||'').split(',').map(x=>x.trim()).filter(Boolean),audience_notes:f.get('audience_notes')?.trim()||null};const {error}=await db.from('recruiting_campaigns').insert(payload);if(error){document.getElementById('campaignMessage').textContent=error.message;return;}document.getElementById('adsModal').classList.remove('open');await load();}
  async function generate(id){const b=document.querySelector(`[data-generate="${id}"]`);if(b){b.disabled=true;b.textContent='KI generiert …';}const {data,error}=await db.functions.invoke('generate-recruiting-campaign',{body:{campaign_id:id}});if(error||data?.error)alert(error?.message||data.error);await load();}
  async function approve(id){const {data:{user}}=await db.auth.getUser();const now=new Date().toISOString();const {error}=await db.from('recruiting_campaigns').update({status:'approved',approved_at:now,approved_by:user?.id,updated_at:now}).eq('id',id);if(error)return alert(error.message);await db.from('campaign_approvals').insert({organization_id:organizationId,campaign_id:id,status:'approved',decided_by:user?.id,decided_at:now});await load();}
  function showPackage(id){const c=campaigns.find(x=>x.id===id);const p=c?.generated_package;if(!p)return;document.getElementById('adsModalTitle').textContent=c.name;document.getElementById('adsModalContent').innerHTML=`<div class="ads-package"><section><span class="badge blue">${esc(p.campaign_angle)}</span><h3 style="margin-top:12px">Strategie</h3><p>${esc(p.strategy_summary)}</p></section><div class="ads-package-grid"><section><h3>Hooks</h3><div class="variant-list">${p.hooks.map(x=>`<div class="variant-item">${esc(x)}</div>`).join('')}</div></section><section><h3>Headlines</h3><div class="variant-list">${p.headlines.map(x=>`<div class="variant-item">${esc(x)}</div>`).join('')}</div></section></div><section><h3>Anzeigentexte</h3><div class="variant-list">${p.primary_texts.map(x=>`<div class="variant-item">${esc(x)}</div>`).join('')}</div></section><section><h3>Creative-Briefings</h3><div class="variant-list">${p.creative_briefs.map(x=>`<div class="variant-item creative-brief"><b>${esc(x.format)}</b><div><strong>${esc(x.angle)}</strong><p>${esc(x.visual)}</p><small>${esc(x.overlay)}</small></div></div>`).join('')}</div></section><section><h3>Compliance</h3><div class="variant-list">${p.compliance_notes.map(x=>`<div class="variant-item">${esc(x)}</div>`).join('')}</div></section></div>`;document.getElementById('adsModal').classList.add('open');}
  const observer=new MutationObserver(injectView);observer.observe(document.body,{childList:true,subtree:true});injectView();
})();